name: Go Warrior CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "TODO"